# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Parstagram_IOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Parstagram
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod "Parse"
  pod "MessageInputBar"



  target 'Parstagram_IOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Parstagram_IOSUITests' do
    # Pods for testing
  end

end